Fix up stale gp_default_storage_options comment
After Postgres 12 merge the GUC to set default table type was moved to
default_table_access_method as hinted by the error message.

  SET gp_default_storage_options='appendonly=true';
  ERROR:  invalid storage option "appendonly"
  HINT:  For table access methods use "default_table_access_method" instead.

Instead seems one should run:

  SET default_table_access_method='ao_row';

Remove the stale comment that suggested otherwise.