Remove extraneous verify_and_replace_mbstr()
Historical commit "verify messages are correctly encoded before logging"
was added in 2011 to address the issue where utf multi-byte
character in the log causes error as below:

select * from gp_toolkit.gp_log_database breaks with an error
ERROR: invalid byte sequence for encoding "UTF8": 0xd022 (seg4 slice1 gpnode2:50001 pid=18825)
DETAIL: External table __gp_log_segment_ext, line 158 of file execute:cat $GP_SEG_DATADIR/pg_log/*.csv

After backporting community fix 16e3ad5d143, the above issue is solved
so the historical commit is no longer needed.
This change now aligns elog.c with upstream elog.c

Co-authored-by: Soumyadeep Chakraborty <soumyadeep2007@gmail.com>