gpcheckcat: list is unhashable, convert it to a string
`j[i]`, could be the query result of array_agg(), which is a unhashable
list, convert it to a string first.

```
>>> row_of_ids = [[0,1],[1,2]]
>>> colset = set(j for j in row_of_ids)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unhashable type: 'list'
```

```
>>> row_of_ids = [[0,1],[1,2]]
>>> colset = set(str(j) for j in row_of_ids)
>>>
```

Note that since PyGreSQL 5.0 this method will return the values of array
type columns as Python lists.

ref: https://pygresql.org/contents/pg/query.html