Fix python import and syntax warning
It seems that CommandNotFoundException was not imported and can cause an
error:
  except CommandNotFoundException as e:
      NameError: name 'CommandNotFoundException' is not defined

Python is giving a warning that `e` in the code above is not being used,
so remove it.

I also noticed that we are using the package `sys` without importing it
and could cause an error in the future, so import that.