Don't reuse AO block if the corresponding segment file was closed
ERROR:  append-only table version -1 is invalid

Requires plan containing a Bitmap Index NL join with bir (containing more than
1 tuple) on the outer side and yolo (with 2 aoseg files, the latter of which is
empty) on the inner side:

```
 Gather Motion 3:1  (slice1; segments: 3)
   ->  Nested Loop Left Join
         Join Filter: true
         ->  Seq Scan on bir
         ->  Bitmap Heap Scan on yolo
               Recheck Cond: (a = bir.a)
               ->  Bitmap Index Scan on yolo_idx
                     Index Cond: (a = bir.a)
```

Co-authored-by: Ashwin Agrawal <aashwin@vmware.com>
Co-authored-by: Shreedhar Hardikar <shardikar@vmware.com>
Co-authored-by: Jesse Zhang <sbjesse@gmail.com>