Wdeprecated-copy: delete default copy-constructor
Instead of the C++98 hackery of declared-but-undefined-private-cctor

Original error:
In file included from ../libgpos/server/src/unittest/gpos/common/CSyncHashtableTest.cpp:23:
../libgpos/server/include/unittest/gpos/common/CSyncHashtableTest.h:154:6: error: definition of implicit copy assignment operator for 'SElem' is deprecated because it has a user-declared copy constructor [-Werror,-Wdeprecated-copy]
                                        SElem
                                        ^