WIP: working on ICW vacuum_gp
Fixed Issues:
Relcache fixed
SEGV on missing heap_endscan fixed

Blocked on:
ERROR:  Unexpected EOF for relation name ao_t1, relfilenode 24936, segment file
0. EOF from gp_persistent_relation_node 119488 greater than current EOF 0
(appendonlyam.c:595)  (seg0 127.0.0.1:25432 pid=39698)

Signed-off-by: Xin Zhang <xzhang@pivotal.io>