Fix gsutil command failed due to wrong dependency location
After switched python3.9 to python3.6, `gsutil` command cannot work on RHEL8
image, it will have the following error:

```
  File "/usr/lib/python3.6/site-packages/urllib3/exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import (
ModuleNotFoundError: No module named 'urllib3.packages.six'
```
By default the RHEL8 system has the package `urllib3` installed under
`/usr/lib/python3.6`, when installing `gsutil`,the dependencies are installed
under `/usr/local/lib/python3.6`, so `gsutil` cannot find dependencies when
calling `urllib3`. In order to fix the above error, need to uninstall and
reinstall urllib3.

Authored-by: Ning Wu <ningw@vmware.com>