Wdeprecated-copy: substitue default copy ctor for user-defined
The user-defined copy constructor is effectively doing what the default
one would do. Defaulting it would fix the error of using a default
copy-assignment operator elsewhere. We should probably also explicitly
default that here, but leaving that for another day.

Original error:
> In file included from CJoinOrderDPv2.cpp:28:
>
../../../../../../src/backend/gporca/libgpopt/include/gpopt/xforms/CJoinOrderDPv2.h:334:5:
error: definition of implicit copy assignment operator for
'SGroupAndExpression' is deprecated because it has a user-declared copy
constructor [-Werror,-Wdeprecated-copy]
>                                 SGroupAndExpression(const SGroupAndExpression &other) : m_group_info(other.m_group_info),
>                                 ^
> CJoinOrderDPv2.cpp:921:24: note: in implicit copy assignment operator
for 'gpopt::CJoinOrderDPv2::SGroupAndExpression' first required here
>                 left_child_expr_info = GetBestExprForProperties((*left_group_info_array)[left_ix], left_reqd_properties);
>                                      ^
> 1 error generated.