Fix pg_dump compilation for Windows client
The recent pg_dump fixes to handle external partitions introduced some
compilation failures for Windows. Specifically, the errors were:
error C2057: expected constant expression
error C2466: cannot allocate an array of constant size 0
error C2133: 'lookupSubRootHierarchyIndex': unknown size

Fix the issue by creating the int array with pg_malloc. Also fix up a
minor issue where a string was being instantiated in a weird way which
was the result of improper commit splitting (the two commits
referenced below were once a single commit but I split them up to make
it more easier to understand).

GPDB commit references:
https://github.com/greenplum-db/gpdb/commit/8ecf11fa6eb936afa6875da76fd82332dfb793d2
https://github.com/greenplum-db/gpdb/commit/ca97e829b1403a0e72914a6aa5afc788f9de4ddc