add GPDB 6X centos7 FIPS python regression test
For Greenplum 6X on centos7 in a FIPS enabled environment our python
utilities would log the following error.

ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/usr/local/greenplum-db-devel/ext/python/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/greenplum-db-devel/ext/python/lib/python2.7/hashlib.py", line 109, in __get_openssl_constructor
    return __get_builtin_constructor(name)
  File "/usr/local/greenplum-db-devel/ext/python/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5

This adds a regression test and was inspired from the following 5X
commit b07b2a23.

Co-authored-by: Mark Sliva <msliva@pivotal.io>