Fix parser algorithm for setting distribution key column numbers in gp_distribution_policy relation for inherited tables in GP5X (GP6X is ok). Query planes with GPORCA caused segmentation fault because of out of range column numbers and postgres optimizer simply returned error before current patch. For example:
create table ta (a int) distributed randomly;
create table tb (a int, b int) inherits (ta) distributed by (b);

set optimizer=on;
insert into tb values(0, 0);
-- Segmentation fault

set optimizer=off;
insert into tb values(0, 0);
-- ERROR: no tlist entry for key 3 (cdbmutate.c:1484)

select attrnums from gp_distribution_policy where localoid = 'tb'::regclass;
 attrnums
----------
{3}
(1 row)

Also a check for setting non-hashable distribution key from a
parent table in an inherited one didn't work.

create table tc (a point) distributed randomly;
create table td (b int) inherits (tc) distributed by (a);

select * from td;
ERROR:  could not find mergejoinable = operator for type 600 (pathkeys.c:1174)

Co-authored-by: Vasiliy Ivanov <7vasiliy@gmail.com>