[modernize] Use nullptr
NULL is not actually a pointer (surprise!), but an "integral constant
that evaluates the zero" [2]. Practically, that means in most mainstream
implementations, we get a "long int". The fact that GCC / libstdc++ has
NULL #define'd to a magic keyword __null [1] makes it no better: it
merely guarantees that the integer has a type that can fit in a pointer
(read: accommodating obscure architectures where "long int" is 32 bit
but pointers are 16 bit).

This patch set converts all live usage of "NULL" to the new nullptr
keyword.

I stumbled on this while working on the reference count refactoring,
where having CAutoP accept "any U* that converts to T*" blew up
spectacularly around the call sites with a "NULL": guess what, it's not
a pointer! A snippet of example error message:

> In file included from /usr/include/unistd.h:226,
>                  from ../libgpos/include/gpos/common/clibwrapper.h:20,
>                  from ../libgpos/include/gpos/string/CWStringBase.h:14,
>                  from ../libgpos/include/gpos/string/CWString.h:14,
>                  from ../libgpos/include/gpos/string/CWStringStatic.h:15,
>                  from ../libgpos/include/gpos/io/COstream.h:17,
>                  from ../libgpos/include/gpos/io/COstreamBasic.h:14,
>                  from ../libgpos/include/gpos/utils.h:19,
>                  from ../libgpos/include/gpos/common/CList.h:21,
>                  from ../libgpos/include/gpos/common/CSyncHashtable.h:25,
>                  from ../libgpos/include/gpos/memory/CMemoryPoolManager.h:17,
>                  from ../libgpos/include/gpos/memory/CAutoMemoryPool.h:24,
>                  from ../libgpos/server/src/unittest/gpos/common/CAutoPTest.cpp:16:
> ../libgpos/server/src/unittest/gpos/common/CAutoPTest.cpp: In static member function ‘static gpos::GPOS_RESULT gpos::CAutoPTest::EresUnittest_Basics()’:
> ../libgpos/server/src/unittest/gpos/common/CAutoPTest.cpp:79:9: error: no match for ‘operator=’ (operand types are ‘gpos::CAutoP<char>’ and ‘long int’)
>    79 |  asz2 = NULL;
>       |         ^~~~

[1] https://gcc.gnu.org/onlinedocs/libstdc++/manual/support.html#std.support.types.null
[2] https://en.cppreference.com/w/cpp/types/NULL