Fix ic_proxy compilation for when HOST_NAME_MAX is unavailable
When compiling proxy interconnect code on MacOS, it fails to compile
with the following error:
```
In file included from ic_proxy_main.c:23:
./ic_proxy_addr.h:35:17: error: use of undeclared identifier 'HOST_NAME_MAX'
        char            hostname[HOST_NAME_MAX];        /* hostname or IP */
                                 ^
ic_proxy_main.c:112:14: error: use of undeclared identifier 'HOST_NAME_MAX'
                char            name[HOST_NAME_MAX];
                                     ^
ic_proxy_main.c:168:14: error: use of undeclared identifier 'HOST_NAME_MAX'
                char            name[HOST_NAME_MAX] = "unknown";
```

Some systems like FreeBSD or MacOS do not define HOST_NAME_MAX so we
need to define it ourselves. Using the POSIX value of 255 seems to be
a safe fallback value so define it as such if HOST_NAME_MAX is
unavailable.