gpcloud: be compatible with OpenSSL 1.1.0+
    src/s3utils.cpp:16:14: error: aggregate ‘HMAC_CTX hmac’ has incomplete type and cannot be defined
         HMAC_CTX hmac;
                  ^~~~
    src/s3utils.cpp:17:24: error: ‘HMAC_CTX_init’ was not declared in this scope
         HMAC_CTX_init(&hmac);
                            ^
    src/s3utils.cpp:22:27: error: ‘HMAC_CTX_cleanup’ was not declared in this scope
         HMAC_CTX_cleanup(&hmac);

HMAC_CTX_init() was totally deprecated from 1.1.0, this fixes it.