Avoid re-executing if all tuples of the plan have been emitted.
On postgres, holdable cursor will rerun the executor after rewinding to put all
tuples in tuplestore during commit for later access, but for gpdb we do not
support backwards scanning so we just continue executing without rewinding the
executor, this could lead to some issues since some executor nodes are not
written or designed for the case that previously the plan has emitted all tuples.

Typical issues are seen as below:

1. assert failure (in execMotionSortedReceiver())
FailedAssertion("!(!((heap)->bh_size == 0) && heap->bh_has_heap_property)", File: "binaryheap.c"

2. elog(ERROR) like below.
ERROR:  cannot execute squelched plan node of type: 232 (execProcnode.c:887)