Change tanzunet concourse resource
When there is a change in tanzunet release, for example, append
a new product to the existing tanzunet release, the
pivotalcf/pivnet-resource will fail by:
ERROR: provided fingerprint: '2023-09-21T19:51:29.452Z' does not match actual fingerprint (from pivnet): '2023-09-21T19:54:18.155Z' - pivnet does not support downloading old versions of a release
So change to releng team's tanzunet concourse resource:
gcr.io/data-gpdb-public-images/tanzunet-concourse-resource
to work around the error.

Also remove check-creds since it make the fly command wait for long
time.

Authored-by: Shaoqi Bai <bshaoqi@vmware.com>