Fix incorrect returnvalue in ExecutePlan fast-path
Commit 00607099901c14aa8d41ca85b9c030552f6c0f5e backported a bugfix for re-
execution of holdable cursors. In master, ExecutePlan is a void function
but in 5X_STABLE it is defined as returning a TupleTableSlot pointer. Fix
the fast-path exit by explicitly returning NULL since the current coding
yields a compiler error on Clang (gcc throws a warning instead):

execMain.c:2843:3: error: non-void function 'ExecutePlan' should return
                          a value [-Wreturn-type]
                return;
                ^
1 error generated.

Reported-by: Jesse Zhang <jzhang@pivotal.io>