Fixed cs-uao/uao_load TINC tests
Manually disabled the ESCAPE delimiter because it caused the below error:
ERROR|could not run SQL "create external table ext_gpload_67e139de_b105_11e6_820f_38c9863100f8(id int,name text,sponsor text)
location('gpfdist://localhost:8082//<tinchome>/tincrepo/mpp/gpdb/tests/storage/uao/uao_load/data/*.txt')
format'text' (delimiter ';' null '\\N' escape '\\' ) log errors segment reject limit 25 ":
ERROR:  escape must be a single character, or [OFF/off] to disable escapes

We are testing uao here, not gpload, so this difference in behavior
between gpdb4/gpdb5 is not relevant for us to investigate.
http://gpdb.docs.pivotal.io/4390/client_tool_guides/load/unix/gpload.html#topic1__cfescape