contrib: Add missing code and testcases for ltree
Add the missing code and testcases from upstream to make the ltree
contrib module complete. With this the module builds and tests.

The ignore block in the test case is to avoid a large diff in the
expected file since the test in question fails on the below error
in Greenplum:

  ERROR:  UNIQUE and DISTRIBUTED RANDOMLY are incompatible