GUC: Force drop primary/unique keys of child partitions
When primary and unique key constraints are added to a partition
hierarchy with an ALTER TABLE ADD statement on the root table, the
auto-generated name of the constraint differs on the partition root vs
the partition children.  As a result, when the same constraint is
dropped from the parent, the constraint is NOT dropped from the
partition children. To make matters worse, any attempt at dropping the
constraint from the children directly, results in:
ERROR:  can't drop a constraint from <child_table_name>; it is part of a partitioned table
HINT:  You may be able to perform the operation on the partitioned table as a whole.

The above was first raised in issue: #3750 and was fixed in 6X+ by #7047
which employs large changes to constraint and partition table
infrastructure, making it not viable to backport.

Furthermore, renaming the constraints is not viable as a workaround, as
renaming constraints is not supported in 5X.

Thus, this commit adds gp_enable_drop_key_constraint_child_partition, a
GUC that provides the user a way to drop the primary/unique key
constraint directly from the partition children.

Note: the GUC does not apply to:
i) CHECK constraints - they don't have the naming inconsistency
ii) FOREIGN KEY constraints - they are not auto-created on partition
children.
iii) NOT NULL constraints = they are not auto-created on partition children.

Furthermore, the GUC should not be necessary for primary/unique key
constraints added at table creation time - as any constraints added at
table creation time don't suffer from the naming inconsistency described
above. Thus dropping such constraints from the root should automatically
drop the constraints from the children.

Co-authored-by: Jimmy Yih <jyih@vmware.com>