Fix issue with getting the session user name running the binary
- backporting based on commit: 241672bb758774b29af7c791b8615526551edccf
- additional fix: if you logged in as root and switch to different user running
  `gpsd` or `minirepro` binary you will not get the user running the
binary. `os.getlogin()` gives you user logged in on the controlling
terminal of the process. So you end up getting following error:

```
$ postgres --gp-version
postgres (Greenplum Database) 6.26.1 build
commit:0ed93c8b0cd523fc85d49b245fe901c063cf3a0b

$ whoami
gpadmin

$ gpsd gpadmin
Traceback (most recent call last):
  File "/usr/local/greenplum-db-6.26.1/bin/gpsd", line 289, in <module>
    main()
  File "/usr/local/greenplum-db-6.26.1/bin/gpsd", line 238, in main
    with closing(pgdb.connect(connectionString)) as connection:
  File "/usr/local/greenplum-db-6.26.1/lib/python/pygresql/pgdb.py",
line 483, in connect
    dbtty, dbuser, dbpasswd)
pg.InternalError: FATAL:  no pg_hba.conf entry for host
"xx.xx.xx.xx", user "root", database "gpadmin", SSL off
```

Authored-by: Gaurab Dey <gaurabd@vmware.com>