[7X] Fix hardcoded schema in partition creation DDL.
Historically, Greenplum is hardcoding the schema when looking up the '+'
operator for the partition creation DDL `(START (XXX) END (YYY) EVERY (ZZZ))`.

This patch simply removes the hardcoded schema name which is similar to
the logic behind processing of `BETWEEN XXX AND YYY` syntax. When evaluating
the `BETWEEN XXX AND YYY` clause, PostgreSQL looks up the `'>='` and `'<='`
operators in the current searching path.

e.g.,

```
CREATE TYPE myint;
CREATE FUNCTION myint_in(cstring) RETURNS myint AS 'int4in' LANGUAGE INTERNAL IMMUTABLE STRICT;
CREATE FUNCTION myint_out(myint) RETURNS cstring AS 'int4out' LANGUAGE INTERNAL IMMUTABLE STRICT;
CREATE TYPE myint (INPUT=myint_in, OUTPUT=myint_out, passedbyvalue, internallength=4);
CREATE FUNCTION myint_lt(myint, myint) RETURNS boolean AS 'int4lt' LANGUAGE INTERNAL IMMUTABLE STRICT;
CREATE FUNCTION myint_le(myint, myint) RETURNS boolean AS 'int4le' LANGUAGE INTERNAL IMMUTABLE STRICT;
CREATE FUNCTION myint_gt(myint, myint) RETURNS boolean AS 'int4gt' LANGUAGE INTERNAL IMMUTABLE STRICT;
CREATE FUNCTION myint_ge(myint, myint) RETURNS boolean AS 'int4ge' LANGUAGE INTERNAL IMMUTABLE STRICT;
CREATE FUNCTION myint_eq(myint, myint) RETURNS boolean AS 'int4eq' LANGUAGE INTERNAL IMMUTABLE STRICT;
CREATE FUNCTION myint_ne(myint, myint) RETURNS boolean AS 'int4ne' LANGUAGE INTERNAL IMMUTABLE STRICT;
CREATE FUNCTION myint_pl_myint(myint, myint) RETURNS myint   AS 'int4pl' LANGUAGE INTERNAL IMMUTABLE STRICT;
CREATE OPERATOR < (LEFTARG=myint, RIGHTARG=myint, PROCEDURE=myint_lt, COMMUTATOR= >, NEGATOR= >=, RESTRICT=scalarltsel, JOIN=scalarltjoinsel);
CREATE OPERATOR > (LEFTARG=myint, RIGHTARG=myint, PROCEDURE=myint_gt, COMMUTATOR= <, negator= <=, RESTRICT=scalargtsel, JOIN=scalargtjoinsel);
CREATE OPERATOR <= (LEFTARG=myint, RIGHTARG=myint, PROCEDURE=myint_le, COMMUTATOR= >=, NEGATOR= >, RESTRICT=scalarltsel, JOIN=scalarltjoinsel);
CREATE OPERATOR >= (LEFTARG=myint, RIGHTARG=myint, PROCEDURE=myint_ge, COMMUTATOR= <=, NEGATOR= <, RESTRICT=scalargtsel, JOIN=scalargtjoinsel);
CREATE OPERATOR = (LEFTARG=myint, RIGHTARG=myint, PROCEDURE=myint_eq, COMMUTATOR= =, NEGATOR= <>, RESTRICT=eqsel, JOIN=eqjoinsel, hashes, merges);
CREATE OPERATOR <> (LEFTARG=myint, RIGHTARG=myint, PROCEDURE=myint_ne, COMMUTATOR= <>, NEGATOR= =, RESTRICT=neqsel, JOIN=neqjoinsel, merges);
CREATE FUNCTION bt_myint_cmp (myint, myint) RETURNS int AS 'btint4cmp' LANGUAGE INTERNAL IMMUTABLE STRICT;
CREATE OPERATOR CLASS bt_myint_ops DEFAULT FOR TYPE myint USING btree family integer_ops AS
  operator 1 <,
  operator 2 <=,
  operator 3 =,
  operator 4 >=,
  operator 5 >,
  FUNCTION 1 bt_myint_cmp (myint, myint);
CREATE CAST (int AS myint) WITHOUT FUNCTION AS IMPLICIT;

CREATE TABLE t(i myint);

-- Operator '<=' and '>=' exist in the current search_path.
SELECT * FROM t WHERE i BETWEEN 1 AND 2;

-- Change the search_path and PostgreSQL cannot find the operator.
SET search_path TO '';
SELECT * FROM public.t WHERE i BETWEEN 1::public.myint AND 2::public.myint;

ERROR:  operator does not exist: public.myint >= public.myint
```