Expose WorkFileUsagePerQuery definition to match API
Commit dfee2ff794dc2a exposed workfile_mgr_cache_entries_get_copy()
which returns a structure containing WorkFileUsagePerQuery entries,
but the definition of WorkFileUsagePerQuery was not make public. A
forward declaration was placed in the workfile_mgr.h file but it
suffered from a redefinition warning (in clang at least):

workfile_mgr.c:93:3: warning: redefinition of typedef
					 'WorkFileUsagePerQuery' is a C11 feature
					 [-Wtypedef-redefinition]
} WorkFileUsagePerQuery;
  ^
../../../../src/include/utils/workfile_mgr.h:25:38:
					note: previous definition is here
typedef struct WorkFileUsagePerQuery WorkFileUsagePerQuery;
                                     ^
Fix by moving the WorkFileUsagePerQuery definition to the header
from which is moved in f1ef3668a8f01a3. If we expose an API which
returns data in the struct we need to also make the definition
available to callers.