Fix log_errors related issue while creating pxf_fdw extension
On an ARM64 machine, CREATE EXTENSION pxf_fdw fails with :
ERROR:  the log_errors option cannot be set without reject_limit

In pxf_fdw_validator(), the variable log_errors is declared bool, but
it is initialized with -1. Since bool seems to be now a built-in type,
it's definition is implementation dependent, and it's possible that on
ARM, it is defined as unsigned char. Because, through debugger it
could be seen that log_errors's value is 255 when it was assigned -1.
And because (log_errors != -1) condition returns true, we get the
error "log_errors option cannot be set without reject_limit" even when
log_errors option was not specified while creating the extension.
Due to this, all pxf_fdw tests were failing on ARM64.

If log_errors is specified, set log_errors to true rather than to
defGetBoolean(def) value. And rename log_errors to log_errors_set to
reflect that its purpose is not to store the log_errors value, but
rather to denote whether log_errors option was specified.