Wdeprecated-copy: Remove explicit copy-assignment operator
This partly addresses a deprecation warning (-turned errors) where
copy-assignment and copy-constructor should either both be user-defined,
or both be default.

Original error:

>
../../../../../../src/backend/gporca/libgpos/include/gpos/common/CDouble.h:115:20:
error: definition of implicit copy constructor for 'CDouble' is
deprecated because it has a user-declared copy assignment operator
[-Werror,-Wdeprecated-copy]
>                         inline CDouble& operator=(const CDouble &right)
>                                         ^
>
../../../../../../src/backend/gporca/libgpos/include/gpos/common/CDouble.h:125:24:
note: in implicit copy constructor for 'gpos::CDouble' first required
here
>                 return CDouble(left.m_d + right.m_d);
>                        ^
> 1 error generated.