Wdeprecated-copy: default copy-assignment
Here the solution is the opposite of what one usually reaches for: we
cannot just default the copy constructor, because the user-defined one
actually is doing some non-default construction there. So instead we
default the copy-assignment operator.

Original error:
> In file included from ../libgpos/server/src/unittest/gpos/common/CSyncHashtableTest.cpp:23:
> ../libgpos/server/include/unittest/gpos/common/CSyncHashtableTest.h:154:6: error: definition of implicit copy assignment operator for 'SElem' is deprecated because it has a user-declared copy constructor [-Werror,-Wdeprecated-copy]
>                                         SElem
>                                         ^
> ../libgpos/server/src/unittest/gpos/common/CSyncHashtableTest.cpp:97:13: note: in implicit copy assignment operator for 'gpos::CSyncHashtableTest::SElem' first required here
>                 rgelem[i] = SElem(i, i);
>                           ^
> In file included from ../libgpos/server/src/unittest/gpos/common/CSyncHashtableTest.cpp:13:
> In file included from ../libgpos/include/gpos/base.h:21:
> In file included from ../libgpos/include/gpos/memory/CMemoryPool.h:31:
> ../libgpos/include/gpos/common/CLink.h:23:4: error: definition of implicit copy assignment operator for 'SLink' is deprecated because it has a user-declared copy constructor [-Werror,-Wdeprecated-copy]
>                         SLink(const SLink&);
>                         ^
> ../libgpos/server/include/unittest/gpos/common/CSyncHashtableTest.h:68:11: note: in implicit copy assignment operator for 'gpos::SLink' first required here
>                         struct SElem
>                                ^
> ../libgpos/server/src/unittest/gpos/common/CSyncHashtableTest.cpp:97:13: note: in implicit copy assignment operator for 'gpos::CSyncHashtableTest::SElem' first required here
>                 rgelem[i] = SElem(i, i);
>                           ^
> 2 errors generated.