Undelete the copy constructor of SLink
We need the (default, implicit) copy assignment elsewhere in SElem.
The combination of a user-declared (even deleted) copy constructor and
an implicit copy assignment operator is deprecated. Fixing it appeases a
Clang 13 warning:

> In file included from ../src/backend/gporca/libgpos/server/src/unittest/gpos/common/CSyncHashtableTest.cpp:13:
> In file included from ../src/backend/gporca/libgpos/server/include/unittest/gpos/common/CSyncHashtableTest.h:14:
> In file included from ../src/backend/gporca/libgpos/include/gpos/base.h:20:
> In file included from ../src/backend/gporca/libgpos/include/gpos/memory/CMemoryPool.h:29:
> ../src/backend/gporca/libgpos/include/gpos/common/CLink.h:20:2: error: definition of implicit copy assignment operator for 'SLink' is deprecated because it has a user-declared copy constructor [-Werror,-Wdeprecated-copy]
>         SLink(const SLink &) = delete;
>         ^
> ../src/backend/gporca/libgpos/server/include/unittest/gpos/common/CSyncHashtableTest.h:124:43: note: in implicit copy assignment operator for 'gpos::SLink' first required here
>                 SElem &operator=(const SElem &) = default;
>                                                         ^
> ../src/backend/gporca/libgpos/server/src/unittest/gpos/common/CSyncHashtableTest.cpp:85:13: note: in defaulted copy assignment operator for 'gpos::CSyncHashtableTest::SElem' first required here
>                 rgelem[i] = SElem(i, i);
>                           ^
> 1 error generated.