Fix build error for latest conan
I see error while trying to build gpdb 5.4.1

```
[gpadmin@mdw depends]$ make -j4
CONAN_USER_HOME=/tmp/gpdb-5.4.1/depends conan install --build=missing conanfile_orca.txt
ERROR: Conanfile not found!
```

Without `-f` key conan interpret last arg as path to the directory, not as conanfile!
Obvious fix. BTW: it was fine in December 2017, but seems latest conan use more strict arg parser.